@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

Person(user, "User", "Uses the TDD-With-GPT plugin")
System(vscode, "VS Code IDE", "Hosts the plugin")
System(plugin, "TDD-With-GPT", "Plugin that helps coding by using GPT APIs")

Rel(user, vscode, "Interacts with")
Rel(vscode, plugin, "Hosts")
@enduml
